### ISSUE TITLE
Create project logo

### ISSUE THREAD

**Issue by Nutomic** [Nutomic/ibis#19]
I definitely need help with this.

**Comment by dessalines** [comment]
I'd recommend just going with one of these [free ibis ones](https://www.flaticon.com/search?type=icon&search-group=all&word=ibis), then eventually as this takes off, you can ask for contributions again.

**Comment by Pome-ro** [comment]
So I took a crack at designing a logo/icon for Ibis. Love your work on Lemmy and this project is exciting too. 

This is a PNG but I have an SVG file for it. If this is better suited as a concept that can be iterated on by others that's great too. 

Just something I had in my head that I wanted to share.

![Ibis.png](https://github.com/Nutomic/ibis/assets/7016247/85573b0e-6c21-4041-980a-f1ae3e88a39d)

**Comment by Nutomic** [comment]
Thanks @Pome-ro, Ive added that logo to the site and the readme. If you still have the svg please share it, then I will add it to the repository as well. Sorry for taking so long with this.

**Comment by wakest** [comment]
@Pome-ro would you share the SVG of this? I would love to add it to [iconography.fediverse.info](https://iconography.fediverse.info)
