### ISSUE TITLE
Articles with none-standard names break federation and can't be accessed

### ISSUE THREAD

**Issue by Demigodrick** [Nutomic/ibis#25]
See https://wiki.lemmy.zip/article/![](https://lemmy.zip/pictrs/image/75b9eaf4-53bb-4922-bf7b-2126d45a380b.webp)

Page won't load and adding /edit to the link doesn't work either.

 Also causes an issue with federation when trying to access the site from a remote site:
![Screenshot_20240314_004421_Firefox Beta](https://github.com/Nutomic/ibis/assets/117108241/db4a234f-cbd7-4fcc-a5c5-f2342150138d)
 
Either need the ability to handle this, or validating the title isn't nonsense/a url/none standard

**Comment by Nutomic** [comment]
It seems like only `/` causes problems as it breaks url parsing. Im rejecting that now.
