### ISSUE TITLE
What happens in case of conflict regarding process, style or "objectivity"

### ISSUE THREAD

**Issue by BMaxV** [Nutomic/ibis#30]
"All articles and edits are automatically synchronized between instances. You can also deploy Ibis on your own server by following the [Setup_Instructions](https://ibis.wiki/article/Setup_Instructions@ibis.wiki)." (from the [announcement](https://ibis.wiki/article/Announcing_Ibis,_the_federated_Wikipedia_Alternative))

One of the things that I dislike about wikipedia is that there a "in-group" that decides on method, style and sometimes what is and what isn't accepted as "objective" or "good source".

And I think it would actually be very helpful to have clearly stated and "objective from their point of view" articles written by certain groups of interest, with a good/easy method to find differences.

So, is there an option to disable this synchronization and to actively, consciously fork the "objective" article?

**Comment by Nutomic** [comment]
If you are an instance admin then you are the "in-group" that decides which edits to allow for your local articles. Of course this depends on mod tools being implemented first, particularly https://github.com/Nutomic/ibis/issues/26 and #27.

If you dont like the way a remote article is written or managed, there is an option to fork it to the local instance under `/article/{title}/actions`. Also articles are only synchronized if one of your users follows that instance.
