### ISSUE TITLE
Decentralized encyclopedic multi-links

### ISSUE THREAD

**Issue by AdamSobieski** [Nutomic/ibis#35]
# Introduction
Ideas are presented for decentralized encyclopedic _multi-links_. These ideas hope to add to the Ibis link syntax.

# User Experience Concepts
## Web Browser Tabs and Tab Groups
Modern Web browsers support tabs and tab groups. Tab groups allow end-users to combine multiple tabs into groups that can be labeled and moved around together. In the simplest case, multi-links, when clicked on, could open one or more articles in one or more browser tabs, these tabs possibly being in a tab group.

## Navigational Popup Widgets
End-users might desire to inspect multi-links before selecting which destinations to navigate to and means of visualizing them and engaging with them are considered here.

As envisioned, navigational popup widgets would contain scrollable lists of specific destinations, each being a hyperlink or resembling an RSS item with an article title, optional site title, site URL, and optional description, summary, or excerpt.

As envisioned, these widgets would support traversing paginated lists of specific destinations. For multi-page contents, this might involve displaying page numbers, providing a means of advancing to next pages, providing means of going back to previous pages, and so forth. Alternatives include dynamically retrieving more items as end-users scroll through them.

As envisioned, search hints or search filters, refinements of searches using articles' and sites' metadata, could be presented in a horizontal list above or below the scrollable list of specific destinations. End-users could manually add, modify, and remove these search filters.

As envisioned, navigational popup widgets would provide a `Refresh` button as some or all of those items in the widget's paginated, scrollable list of items might be the result of a cached search.

As envisioned, a navigational popup widget would have an `Open All` or `Open Top 5` button. This button could become an `Open Selected` button as end-users selected one or more items from the widget's scrollable list of items. Selecting or deselecting multiple items could be achieved by allowing end-users to use the `Ctrl` key and the left mouse button or, in particular for mobile computing scenarios, using checkboxes.

If a navigational popup widget were to contain only one item, the widget could automatically navigate to that item, in either the same or a new tab, possibly after a brief countdown.

If a navigational popup widget were presenting options only on remote sites, it could provide a `Create` button for end-users to create a local version of an article with the contextual title.

Navigational popup widgets could also provide settings buttons for end-users to configure their settings.

## Context Menus
Navigational popup widgets, described above, could, additionally or alternatively, be opened by selecting a menu item on context menus opened upon multi-links in hypertext documents.

## Tooltips
Tooltips could present content pertaining to hyperlinks and multi-links when end-users hovered over them.

## Interactive Link Completion
While authoring documents, editors might want a means of delaying typing the domain or domains in a link. A syntax option could be created for end-users to express that they intend to later complete a link, e.g., `[[title@?]]` or `[[title@...]]`.

As envisioned, after uploading an article or revision containing one or more of these, end-users would be prompted to, for each such link, interactively complete the link, including by means of utilizing an integrated search component. After completing all of the links, their article or revision would be posted.

## Intelligent Code Completion
Article-editing tools could be configured to provide intelligent code completion features for end-users. With code completion, typing `[[title@` and waiting a moment or pressing the `Tab` key would result in a search-enhanced contextual menu for selecting one or more code-completion options, e.g., to enter `[[title@example.com]]`.

# Decentralized Encyclopedic Multi-links
###  From a Local Domain
The following syntax indicates that three local destinations should be opened in three browser tabs, possibly in a tab group.
```
[[{title1, title2, title3}|link text]]
```

### From Multiple Remote Domains
The following syntax indicates that three remote destinations should be opened in three browser tabs, possibly in a tab group.
```
[[{title1@example1.com, title2@example2.com, title3@example.com}|link text]]
```

### Identically-titled
The following syntax indicates that three remote destinations should be opened in three browser tabs, possibly in a tab group.
```
[[title@{example1.com, example2.com, example3.com}]]
```

## Search Integration
This important feature would allow end-users to not have to exhaustively specify sequences of domains.

The following syntax indicates that up to a user-configurable maximal number of browser tabs from an integrated search component, e.g., 5 or 10, would be opened.
```
[[title@{*}]]
```

### Text Queries
Text-query-enhanced searches could be supported via syntax resembling the following.
```
[[title@{*?query=here%20is%20a%20text%20query}]]
```

### Metadata
Decentralized encyclopedic sites and articles could have metadata. Expressiveness could be provided to add metadata-based search filters to searches.
```
[[title@{*?category=Machine%20Learning}]]
```

### Internationalization
Expressiveness could be provided for searching for sites and articles using language-related metadata.
```
[[title@{*?language=en}]]
```

### Automatic Search Parameters
Integrated searches could have search parameters automatically added by configured server nodes. For examples, the server's language could be added to a search and, perhaps, the domain(s) originating a search so that only domains remote to it would have their articles included in the search results.

## Taking a Number of Options that Exist Online
Authors could use integers to express that a multi-link should navigate to the first _n_ valid, available, existing options.

This could be used to express to navigate to the top _n_ search results, e.g., the top 5. The following could return 0, 1, 2, 3, 4, or 5 search results.
```
[[title@5{*}]]
```
This could be used to describe a search which returns 0 or 1 results.
```
[[title@1{*}]]
```
This could be used to return 0, 1, 2, or 3 valid, available, and existing local articles and to navigate to them.
```
[[3{title1, title2, title3}|link text]]
```
This could be used to express to return 0 or 1 results and navigate to it.
```
[[1{title1, title2, title3}|link text]]
```
This could be used to express to return 0 or 1 results and navigate to it.
```
[[title@1{example1.com, example2.com, example3.com}]]
```
The following syntax could be used to express that the multi-link author desires to navigate to a local article, if it exists, and, if not, to navigate to a top search result.
```
[[title@1{/, *}]]
```
The following syntax shows a more complex example which combines a number of previous concepts.
```
[[title@1{/, example.com, *?category=Machine%20Learning&language=en}]]
```

## Red Links
When should red links be presented to end-users for them to create new local articles in decentralized networks of encyclopedia nodes, when articles might already exist elsewhere?

The empty set, `Ø`, resulting from the exhaustion of alternatives, could automatically result in presenting a red link to create a new, local article.

Were this the case, then the following syntax would produce a red link if none of the three specified remote articles existed.
```
[[title@1{example1.com, example2.com, example3.com}]]
```

Were this the case, then the following syntax would produce a red link if the article did not exist locally and could not be found elsewhere through an integrated search component.
```
[[title@1{/, *}]]
```

## Semantics and Relational Algebra
There exist mappings between the semantics of the syntax discussed above and sequences of relational-algebraic operations performed upon lists or sequences of articles' locations on decentralized servers. Pseudocode sketches are provided.

A first example:
```
[[title@1{example1.com, example2.com, example3.com}]]
```
```cs
From("title@example1.com", "title@example2.com", "title@example3.com").Where(x => ExistsOnline(x)).Take(1);
```
A second example:
```
[[title@3{*}]]
```
```cs
Search("title").Where(x => ExistsOnline(x)).Take(3);
```
A third example:
```
[[title@5{example.com, *}]]
```
```cs
From("title@example.com").Concat(Search("title")).Where(x => ExistsOnline(x)).Take(5);
```

# Implementation Concepts
## Generated Hypertext Documents and JavaScript
Link syntax resembling:
```
[[{title1@example1.com, title2@{example2.com, example3.com}, title3@{*}}|link text]]
```

could result in generated hypertext resembling:
```html
<a class="external multi search" href="javascript:f('{title1@example1.com, title2@{example2.com, example3.com}, title3@{*}}')">link text</a>
```

Notice that the validated article-link syntax can be passed through directly to the resultant HTML as the argument to the JavaScript function.

Notice that resultant anchor elements would bear descriptive classes which could be used to style links for end-users.

## Server-side Processing
Some or all multi-links should be processed on server nodes. This would greatly reduce the number of resource existence checks and integrated searches that would need to be performed while allowing decentralized networks of interconnected articles to be organic, resilient, and self-repairing over the course of time.

## Caching Results
With cached results served to clients, populated navigational popup widgets would appear faster for end-users and automatic navigation would occur faster.

A separate client-side syntax should include a means for expressing that portions of results are cached from servers.

In the following client-side syntax example, square-brackets, `[]`, are used to indicate caching.

```html
<a class="external multi search cached" href="javascript:f('[title1@example1.com, title2@example2.com, title3@[cached1.com, cached2.com, cached3.com]]')">link text</a>
```

As envisioned, popup navigational widgets would provide end-users with a `Refresh` button for obtaining fresh results. While there are solutions for allowing end-users to refresh individual multi-links, additionally or alternatively, entire articles could be refreshed by end-users, this involving the simultaneous refreshing of all of the multi-links in an article.

With respect to caching and refreshing, contingencies to consider include that remote encyclopedic domains could be temporarily offline or unavailable and, after durations of time, that they might be permanently offline or unavailable.

## What Links Here
If a "What Links Here" feature is desired for the Ibis platform, refreshing cached articles and/or reprocessing their multi-links could result in typed pings or other update messages to be sent to delinked and newly linked articles.

## Item Display
How might sites' titles and articles' descriptions, summaries, or excerpts be included for display alongside articles' titles and URLs in navigational popup widgets? One idea is to utilize something like URL query-string syntax.

```html
<a class="external multi search cached" href="javascript:f('[title1@example1.com?site=Site%20Title&desc=excerpt%20of%20article, title2@example2.com, title3@[cached1.com, cached2.com, cached3.com]]')">link text</a>
```

## Scripts and Bots
Scripts and bots could wield this multi-link syntax on behalf of end-users and site administrators.

## Options and Alternatives
Variations of, transformations of, the proposed multi-link language syntax are possible while providing end-users with the same expressiveness and capabilities.

Instead of using URL-encoded query strings for storing search parameters and item display parameters,
```
[[title@{*?query=here%20is%20a%20text%20query&language=en}]]
```
other, perhaps more human-readable, techniques could be used. For instances, quotation marks could be utilized.
```
[[title@{*?query="here is a text query"&language="en"}]]
```

Also, instead of reusing the multi-link syntax for client-side JavaScript processing - or varieties thereof - in generated hypertext documents' hyperlinks, JSON data could be generated for a JavaScript function.

**Comment by K4LCIFER** [comment]
> This is too complicated.

There *are* a lot of things in this issue — it could be broken up — but it does raise a question regarding how duplicate articles from other instances will be handled. Like how should an article be linked if there's a local article and multiple duplicate federated articles? That idea is perhaps troublesome as those links aren't necessarily controlled in time, so they may not actually be good sources. Perhaps an article should only have one link, either to itself, or to completely defer to another instance's article.
