### ISSUE TITLE
Redirect

### ISSUE THREAD

**Issue by Doomsdayrs** [Nutomic/ibis#39]
Ability to mark a given term to be redirected elsewhere, for name changes etc

**Comment by Nutomic** [comment]
This would have to be part of a larger feature to allow renaming articles. Which would be very difficult with federation. Not something I plan to add anytime soon.

**Comment by K4LCIFER** [comment]
> [Renaming articles] would be very difficult with federation.

Out of sheer curiosity, what about federation increases the difficulty of such a feature?

**Comment by Nutomic** [comment]
The renaming would have to be federated to all instances, and applied by all of them.
