### ISSUE TITLE
Replace "master" branch with "main"

### ISSUE THREAD

**Issue by Doomsdayrs** [Nutomic/ibis#41]
Isn't it default "main" nowadays anyways?

**Comment by Nutomic** [comment]
Master was the default. Changing the branch name anywhere would be a big hassle and I fail to see any benefit.

**Comment by Doomsdayrs** [comment]
> Master was the default. Changing the branch name anywhere would be a big hassle and I fail to see any benefit.

It would be a greater hassle as time goes on.

The premise is that "master" is utilizing colonizer language & terminology.

"main" is more respective to what the point of the main branch is.
