### ISSUE TITLE
[Enhancement] Bigger editor window

### ISSUE THREAD

**Issue by K4LCIFER** [Nutomic/ibis#51]
Right now, the editor window is quite tiny. I have to resize it every time that I want to edit the article. It should default to, at least, show the full content of the article, or at least a large portion of it.

**Comment by Silver-Sorbet** [comment]
I suggest to maybe move the submit button on the right, so that if the editor window is bigger, the user could still see where the submit button is no matter how long the editor window is

**Comment by K4LCIFER** [comment]
> I suggest to maybe move the submit button on the right, so that if the editor window is bigger, the user could still see where the submit button is no matter how long the editor window is

I think what's most important is that it's in a consistent spot. For example, say the page was rendered like this:
![image](https://github.com/user-attachments/assets/4c607dce-8f15-4426-a9a7-3d9a0169ad37)
I think it'd be good to leave space on the right for potential live rendering of the markdown.

**Comment by Nutomic** [comment]
Ive changed to use size based on the [row count](https://stackoverflow.com/a/17605480), though it doesnt account for line wrapping.
