### ISSUE TITLE
Support alternate text for wikilinks

### ISSUE THREAD

**Issue by K4LCIFER** [Nutomic/ibis#52]
Ibis supports Wikilinks with `[[article-name]]`, but it doesn't appear to support adding alternate text for wikilinks. [Wikilinks](https://en.wikipedia.org/wiki/Help:Link) usually seem to use a vertical bar to Specify alternative text, eg `[[article-name|alternate-text]]`. [Obsidian specifies](https://help.obsidian.md/Linking+notes+and+files/Internal+links) also using `#` to denote headings, eg `[[article-name#heading-in-article|alternate-text]]`.

**Comment by Nutomic** [comment]
The relevant code is [here](https://github.com/Nutomic/ibis/blob/master/src/frontend/markdown.rs#L71), it should be pretty easy for someone to implement this.

**Comment by Nutomic** [comment]
Implemented like this: `[[Main_Page@example.com|My Title]]`
