### ISSUE TITLE
[Enhancement] Show statistics for page visitors.

### ISSUE THREAD

**Issue by K4LCIFER** [Nutomic/ibis#59]
It'd be neat to have statistics similar to Lemmy that shows how many people have been visiting the article. Potentially, you could also show how many people are currently looking at the article.

**Comment by Nutomic** [comment]
Lemmy doesnt have such statistics. In fact its impossible with federation.

**Comment by K4LCIFER** [comment]
> Lemmy doesnt have such statistics. In fact its impossible with federation.

Perhaps I've been misinterpreting what these statistics are saying then?
![image](https://github.com/user-attachments/assets/feb8d330-eddf-40c4-bab5-b5827f66bad6)

Are they not showing visitors? Or is it only showing those who have interacted with something — ie commented, or upvoted?

**Comment by dessalines** [comment]
Those aren't page views, but active participation, as measured by votes, comments, or posts. 

In general if you're going to open up a bunch of issues, you should be willing to work on some of them, so that they can be assigned to you.

**Comment by K4LCIFER** [comment]
> ts impossible with federation.

How does PeerTube track views?
