### ISSUE TITLE
[Bug] Unable to log in

### ISSUE THREAD

**Issue by K4LCIFER** [Nutomic/ibis#64]
The login process is simply failing. When the log in button is pressed, the user credential boxes clear, and the user remains logged out.

**Comment by K4LCIFER** [comment]
Upon further investigation, I think that error is completely unrelated to the login failure as I see that error pop up whenever I load open.ibis.wiki regardless of whether I have just tried logging in. That being said, the login process *is* failing.

**Comment by Nutomic** [comment]
Fixed in https://github.com/Nutomic/ibis/commit/51ada1fc4f457b964196aa65bd624cfd31b24739, there was a dependency update which changed a path and then javascript/wasm files were in the wrong place.
