### ISSUE TITLE
[Bug] Inline math is not rendered

### ISSUE THREAD

**Issue by K4LCIFER** [Nutomic/ibis#65]
For example [[source](https://open.ibis.wiki/article/Gauss's_Law)] 
![image](https://github.com/user-attachments/assets/a983ad6c-6890-4228-b400-7debb71bc1da)

**Comment by Silver-Sorbet** [comment]
I kept the single $ available in case we included Typst later. However, if it's not important right now, I can make it so that $ is inline and $$ is display.

Currently inline is like this: 
`$$E=mc^2$$`

Display is like this:
```
$$
E=mc^2
$$
```

**Comment by K4LCIFER** [comment]
Noted, I'll close this issue then as further changes would be enhancements, and this is expected behavior.
