### ISSUE TITLE
[Bug] Integral symbol in display mode should not be tiny

### ISSUE THREAD

**Issue by K4LCIFER** [Nutomic/ibis#66]
For example [[source](https://open.ibis.wiki/article/Gauss's_Law)]:
![image](https://github.com/user-attachments/assets/3dbb7a1d-94df-4c16-a40a-cc31dc72923d)

I would expect something like this [[source](https://en.wikipedia.org/wiki/Gauss%27s_law)]:
![image](https://github.com/user-attachments/assets/10e75662-e0e9-4a53-86f1-91c3e2455cf4)

**Comment by Silver-Sorbet** [comment]
That's because for some reason, the fonts aren't being loaded. What's weird is that I tested the code on my system and the fonts are being loaded. It's only when I go to the main site that it's like that.

**Comment by Nutomic** [comment]
The release consists of a single binary with embedded files using include_str! or include_bytes! macros. Your code is actually not doing that but only reading from local filesystem, so the fonts are not included in the release.

Can you make a PR to embed the files using https://crates.io/crates/include_dir instead?

Btw is it really necessary to include so many different font files?

**Comment by Silver-Sorbet** [comment]
I thought that maybe including all the file types would help just in case one of them can't be loaded by the browser, but if that's not the case, then yes, not all of them have to be included

**Comment by K4LCIFER** [comment]
Fixed via https://github.com/Nutomic/ibis/pull/68, and implemented in https://github.com/Nutomic/ibis/releases/tag/0.1.4.
