### ISSUE TITLE
Increase the default/initial/minimum height/size of the edit window when creating a new article

### ISSUE THREAD

**Issue by K4LCIFER** [Nutomic/ibis#70]
Currently, when creating a new article, this is the view that the user sees:
![image](https://github.com/user-attachments/assets/a82c3609-38bb-4c85-b69e-a29709f19eea)
To me, this feels rather claustrophobic. I would recommend increasing its eight to make it feel a little more... "open", or "free" for lack of a better word.

This is related to https://github.com/Nutomic/ibis/issues/51.

**Comment by Nutomic** [comment]
This is fixed in main branch
