### ISSUE TITLE
Ibis doesn't comply with CommonMark HTML rendering in markdown

### ISSUE THREAD

**Issue by K4LCIFER** [Nutomic/ibis#75]
The CommonMark spec (v0.31.2) [specifies that raw HTML be rendered as HTML without escaping](https://spec.commonmark.org/0.31.2/#raw-html); however, Ibis is not treating it as such. For example:
![image](https://github.com/user-attachments/assets/206874b7-f09b-45a6-bda4-5d64a4b0e5d9)
https://open.ibis.wiki/article/Test_Article@open.ibis.wiki/diff/d1824834-a1f8-5310-ea2b-5ba157be15be

This may be an issue for [upstream](https://github.com/markdown-it-rust/markdown-it).

**Comment by Nutomic** [comment]
There is an optional plugin for [raw html support](https://docs.rs/markdown-it/latest/markdown_it/plugins/html/index.html) but it is insecure. It would also be more difficult for other users to edit, and Im not sure if its really necessary.

**Comment by K4LCIFER** [comment]
> Im not sure if its really necessary.

It's only necessary if you wish to comply with CommonMark. If you don't wish to support this feature, then Ibis simply doesn't comply with CommonMark — it would instead be a subset.

**Comment by K4LCIFER** [comment]
How come this was closed? I know you said that it would be in the far future, but, to me, that doesn't mean that the issue is necessarily resolved. Closing either means that it's completed, or out of scope. Being in the future doesn't mean that it's out of scope.

**Comment by Nutomic** [comment]
I dont think html should be supported in articles. First of all it would be difficult to prevent security problems, and second it would make editing very difficult for people who are not familiar with html.
