### ISSUE TITLE
Percent encoding is being scrubbed from URI's in the  rendered markdown

### ISSUE THREAD

**Issue by K4LCIFER** [Nutomic/ibis#76]
I was testing text fragment links in [this article](https://open.ibis.wiki/article/Ibis). [This edit](https://open.ibis.wiki/article/Ibis@open.ibis.wiki/diff/58714275-013a-7d56-89aa-b8936e285423) added a URL with percent encodes to jump to a specific bit of text. Unfortunately, this link doesn't work, and, upon investigation, it was found that the percent encodes were being removed from the URL.

So, instead of
```
https://open.ibis.wiki/article/Ibis#:~:text=Nutomic%2Fibis.%20GitHub.%20Accessed%3A%202024-09-15T11%3A02Z.%20https%3A%2F%2Fgithub.com%2FNutomic%2Fibis.
```
It was using the following as the link:
```
https://open.ibis.wiki/article/Ibis#:~:text=Nutomic/ibis. GitHub. Accessed: 2024-09-15T11:02Z. https://github.com/Nutomic/ibis.
```

Weirdly enough, it isn't entirely scrubbing the encodes from the text, because if you edit, they're still there, it's just in the rendered Markdown.

**Comment by K4LCIFER** [comment]
Maybe this is a bug in Firefox. If I simply copy the text from the URL bar (placed there by clicking the link) and re submit it, it will highlight the text as expected. I'm not sure why it doesn't work by clicking the link. It should also be noted that it won't scroll to the text, though this might be a bug in Firefox.

**Comment by Nutomic** [comment]
It looks like you wrote the link wrong in your edit, it should be `[title](url)`. Also there is currently no support for footnotes, but Ive added another plugin for that.

https://github.com/markdown-it-rust/markdown-it-plugins.rs/blob/main/crates/footnote/README.md

**Comment by K4LCIFER** [comment]
> It looks like you wrote the link wrong in your edit, it should be `[title](url)`

The markdown is correct:
```
Ibis is an open-source [[7](https://open.ibis.wiki/article/Ibis#:~:text=Nutomic%2Fibis.%20GitHub.%20Accessed%3A%202024-09-15T11%3A02Z.%20https%3A%2F%2Fgithub.com%2FNutomic%2Fibis.)], federated wiki [1][1.1.1][1.2][2][3][4.1].
```
specifically:
```
[7](https://open.ibis.wiki/article/Ibis#:~:text=Nutomic%2Fibis.%20GitHub.%20Accessed%3A%202024-09-15T11%3A02Z.%20https%3A%2F%2Fgithub.com%2FNutomic%2Fibis.)
```
That is the correct format for a link.

**Comment by K4LCIFER** [comment]
> Also there is currently no support for footnotes, but Ive added another plugin for that.
> 
> https://github.com/markdown-it-rust/markdown-it-plugins.rs/blob/main/crates/footnote/README.md

Hmmm. I'm not sure how I feel about that syntax — it feels rather inelegant.

**Comment by Nutomic** [comment]
Thats just how the existing plugin works. I dont have time to rewrite the code and maintain it myself.

**Comment by K4LCIFER** [comment]
> About the link, do you mean `%20` being replaced with space? Thats just the browser doing [urldecode](https://www.w3schools.com/tags/ref_urlencode.asp) which is completely valid.

Noted. But the browser still isn't reacting to clicking a link that contains text references. For it to work, the URL has to be resubmitted after the link is clicked.

**Comment by Nutomic** [comment]
Its working just fine for me, it jumps to the specified text and highlights it (Firefox 131).

**Comment by K4LCIFER** [comment]
Very weird. I'm in 131.0.3 and it doesn't jump. It doesn't even highlight the text unless I hit enter in the URL bar.

**Comment by K4LCIFER** [comment]
I just did some tests, and Firefox will scroll to a text fragment in Ibis if I manually create a URL, but, it wont scroll to a text fragment from a link within an Ibis article. Try clicking on `[7]` in the first opening paragraph in [this](https://github.com/Nutomic/ibis/issues/76) article. It should jump all the way down to the bottom of the page, but it doesn't.

Side note, I'm not sure if this is a design flaw in Firefox or ibis, but using text fragments multiple times leaves text highlighted on the page if you jump to another piece of text.

**Comment by Nutomic** [comment]
Youre right.

**Comment by Nutomic** [comment]
Closing this as unsupported, anyway you cannot use absolute links which include the domain, because that doesnt work over federation. For example someone reading the article from [ibis.wiki](https://ibis.wiki/article/Ibis@open.ibis.wiki) and clicking on the link gets redirected to open.ibis.wiki which should not happen. To prevent this Im adding an error when linking to the local site.
