### ISSUE TITLE
Ability to create anchors with custom URI's within the article so that a link can jump to them

### ISSUE THREAD

**Issue by K4LCIFER** [Nutomic/ibis#77]
Generally, it would function somewhat similar to [this](https://blog.hubspot.com/marketing/jump-link-same-page). Create an anchor somewhere in the page, then simply reference it with a link. When that link is clicked, the page scrolls to that anchor (and perhaps highlights the element enclosed in the anchor). Perhaps it could be as simple as simply allowing HTML anchors in the markdown ie allow the user to write things like `<a id=this_is_an_id>anchored text</a>` and then reference it with `[text](#this_is_an_id)`, unless a cleaner Markdown-like alternative could be used.

MyST has something similar with references: https://mystmd.org/spec/references

**Comment by Nutomic** [comment]
Anchors should be generated automatically for markdown headings, but it seems that its currently not supported by markdown-it.

**Comment by K4LCIFER** [comment]
While https://github.com/Nutomic/ibis/commit/e7d480098f0c77392fb6a01d4db2b185dc567be5 is nice to have, that isn't what this issue is referring to. This issue seeks the ability to create *custom* anchors — anchors that can be placed *anywhere* in the text — so that a link to them can jump directly to them in the page. The motivation for me is for a references section — it would be nice to click on the reference in the text, and have the page scroll directly to the reference.

**Comment by Nutomic** [comment]
Isnt this exactly what the footnote plugin from https://github.com/Nutomic/ibis/issues/76 does?

**Comment by K4LCIFER** [comment]
> Isnt this exactly what the footnote plugin from #76 does?

The footnote functionality *has* jumping functionality, yes, but it is not an arbitrary anchor — ie an anchor that can be tied to any element. Users shouldn't be tied to the, arguably, rather poor syntax of the footnote for any reference style that they want to use. In my case, it would entirely break the reference format that I've been using.

**Comment by Nutomic** [comment]
A prescriptive syntax is easier to learn for users. If there are multiple ways to do the same thing it becomes confusing and unnecessarily complicated. And like I said, Im relying on existing plugins for markdown functionality, and dont have time to mess with the code myself for such minor differences.

**Comment by K4LCIFER** [comment]
> A prescriptive syntax is easier to learn for users.

That means that you are forcing a citation format on *all* ibis users on *all* instances — that is if you are intending that footnotes be used for references.

> If there are multiple ways to do the same thing it becomes confusing and unnecessarily complicated

I'm not arguing for multiple methods for the same thing, I'm more recommending taking a sandbox style of approach: Provide users with enough syntactical elements so that  they are able to write near any style of article that they desire. In relation to the footnotes, all I'm saying is that not all citation formats follow a format that looks like `[1]`. 

At any rate, in another issue, you mentioned that the URL with text matching jumps to the relevant text and highlights it in your browser, so that functionality plus the ability to write superscripts may be more than sufficient to fill the goal that I'm talking about.
