### ISSUE TITLE
Markdown spoilers

### ISSUE THREAD

**Issue by K4LCIFER** [Nutomic/ibis#78]
Being able to create unique blocks for warnings, or notes, or tips etc. (like [MyST Admonitions](https://mystmd.org/spec/admonitions)) is *extremely* important for Wikis that provide guides rather than encyclopedic knowledge.

**Comment by K4LCIFER** [comment]
Lemmy allows the user to create collapsible "spoilers" with the following syntax:
```
::: spoiler <spoiler title>
hidden text
:::
```
Perhaps Ibis "Admonitions" could use the same format? Something like 
```
::: note <note title>
note text
:::
```
Though there might need to be the ability to add other arguments like what MyST allows.

**Comment by Nutomic** [comment]
So just spoiler tags, thats easy to add.

**Comment by K4LCIFER** [comment]
> So just spoiler tags, thats easy to add.

Err, no. I was simply musing about the possibility of the syntax. This is a bit more of a complex issue — I am not referring to simple spoilers. Please read [this](https://mystmd.org/guide/admonitions). This issue is requesting blocks of the following sorts of types:
![image](https://github.com/user-attachments/assets/403a6c07-6dba-4233-8e7c-91f674341f5f)
For example from [MyST](https://mystmd.org/guide/admonitions):
![image](https://github.com/user-attachments/assets/6c74adf3-dee9-4a24-95d3-1c346d46b8ea)
![image](https://github.com/user-attachments/assets/561d8074-2000-4f65-99e0-e6c3fd5ca25a)
![image](https://github.com/user-attachments/assets/d74467ab-2417-499d-a1f1-cd9e596200ad)
![image](https://github.com/user-attachments/assets/9bc44806-c5c3-4952-8611-c97cb08a852f)
etc.

They could also have the option to be dropdowns, but, for a wiki, that's more of a secondary necessity.

**Comment by Nutomic** [comment]
Related: https://github.com/markdown-it-rust/markdown-it-plugins.rs/issues/22

**Comment by K4LCIFER** [comment]
For more ideas on how the syntax for this can be done, [this is how Obsidian does it](https://help.obsidian.md/callouts).
