### ISSUE TITLE
[META] Consider hosting/mirroring this repository on Codeberg/selfhosted Forgejo

### ISSUE THREAD

**Issue by K4LCIFER** [Nutomic/ibis#79]
Codeberg is, imo, a more ethical alternative to GitHub. Forgejo is open source, and they are working on implementing federation. 

I do fully understand that switching to a more obscure, and less mature code hosting platform may hamper development progress, so I understand if this is a path that will not be explored any time soon. But I think it's, at least, worthy of consideration.

**Comment by Nutomic** [comment]
Done: https://git.join-lemmy.org/nutomic/ibis

**Comment by K4LCIFER** [comment]
> Done: https://git.join-lemmy.org/nutomic/ibis

Interesting that you chose to use Gitea. Out of curiosity, why not Forgejo?

**Comment by K4LCIFER** [comment]
Out of curiosity, I saw this at the bottom of the page:
![image](https://github.com/user-attachments/assets/b462ca6c-bca5-410d-b002-fcaa5febc0d3)
Would you by chance be aware of why this says "gitea" in the version info? Given that Forgejo is a hard fork of Gitea, I would think that they wouldn't use Gitea in the version number.

**Comment by Nutomic** [comment]
No idea, its the official Forgejo release.
