### ISSUE TITLE
Ability to add subscripts and superscripts

### ISSUE THREAD

**Issue by K4LCIFER** [Nutomic/ibis#85]
It would be great to be able to add subscripts and superscripts. There may be an issue regarding the best syntax to use for this, and this may be why [CommonMark hasn't implemented it](https://talk.commonmark.org/t/why-there-is-no-syntax-for-subscript-and-supscript/586/17). Ideally, something like `^` for superscript, and `_` for subscript would be nice, though I'm not sure the best way to go about specifying multiple characters — perhaps `^[]`, and `_[]`? I'm not sure. For reference, [MyST does it like this](https://mystmd.org/guide/typography#subscript-superscript).

**Comment by K4LCIFER** [comment]
Perhaps as a temporary measure, they could simply be implemented with HTML tags, ie `<sup></sup>`, and `<sub></sub>`.

**Comment by Nutomic** [comment]
https://crates.io/crates/markdown-it-sub
https://crates.io/crates/markdown-it-sup

**Comment by K4LCIFER** [comment]
Ahhh so it wraps it in the `^`, or `~`, that's prob a good way to do it. Unfortunate that `~` has to be used for subscripts, but I suppose it makes sense given that [CommonMark specifies](https://spec.commonmark.org/0.31.2/#emphasis-and-strong-emphasis) `_` for emphasis and strong emphasis. It's an unfortunate standard definition, but a definition nonetheless.
