### ISSUE TITLE
Allow users to moderate an article

### ISSUE THREAD

**Issue by K4LCIFER** [Nutomic/ibis#93]
When a user creates an article, they automatically become a moderator of that article. That moderator can then appoint other people to help moderate/maintain the article (eg delete spam edits, bad edits, approve edits, etc.). The moderator would have the authority to delete the article, or control who can edit the article. 

This *might* not be inline with the philosophy of ibis, though, where you'd have the instance acting as a publisher that has say over *all* articles that it contains rather than each article sort of acting of it's own accord.

**Comment by Nutomic** [comment]
Admins have to be able to moderate articles, as they are legally responsible for everything thats hosted on their server. It would be possible to have additional moderators (like community mods on Lemmy), but that would take a lot more work to implement, and my time is limited. So I will focus on more important tasks instead.
